/* Copyright © 2022, Medelför OÜ. All rights reserved. */

#pragma once

#include "Type.h"

class UNREALISTICDOCS_API FArrayType : public FType
{
public:
    const TUniquePtr<FType>& GetElementType() const
    {
        return ElementType;
    }

    void SetElementType(TUniquePtr<FType> NewElementType)
    {
        this->ElementType = MoveTemp(NewElementType);
    }

    void Accept(ITypeVisitor& Visitor) const override
    {
        Visitor.Visit(*this);
    }

    FString GetAutoGeneratedValueTransliteration() const override
    {
        return AutoGeneratedValue;
    }

    ~FArrayType() override = default;

private:
    static const FString AutoGeneratedValue;
    TUniquePtr<FType> ElementType;
};
