/* Copyright © 2022, Medelför OÜ. All rights reserved. */

#pragma once

#include "ApiModel/Function.h"
#include "Type.h"

class UNREALISTICDOCS_API FDelegateType : public FType
{
public:
    FFunction const* GetSignature() const
    {
        return Signature.Get();
    }

    void SetSignature(TUniquePtr<FFunction> NewSignature)
    {
        Signature = MoveTemp(NewSignature);
    }

    bool IsMulticast() const
    {
        return bIsMulticast;
    }

    void SetIsMulticast(bool bNewIsMulticast)
    {
        this->bIsMulticast = bNewIsMulticast;
    }

    void Accept(ITypeVisitor& Visitor) const override
    {
        Visitor.Visit(*this);
    }

    FString GetAutoGeneratedValueTransliteration() const override
    {
        return AutoGeneratedValue;
    }

    ~FDelegateType() override = default;

private:
    static const FString AutoGeneratedValue;
    TUniquePtr<FFunction> Signature;
    bool bIsMulticast = false;
};
