/* Copyright © 2022, Medelför OÜ. All rights reserved. */

#pragma once

#include "Type.h"

class UNREALISTICDOCS_API FMapType : public FType
{
public:
    const TUniquePtr<FType>& GetKeyType() const
    {
        return KeyType;
    }

    void SetKeyType(TUniquePtr<FType> NewKeyType)
    {
        this->KeyType = MoveTemp(NewKeyType);
    }

    const TUniquePtr<FType>& GetValueType() const
    {
        return ValueType;
    }

    void SetValueType(TUniquePtr<FType> NewValueType)
    {
        this->ValueType = MoveTemp(NewValueType);
    }

    void Accept(ITypeVisitor& Visitor) const override
    {
        Visitor.Visit(*this);
    }

    FString GetAutoGeneratedValueTransliteration() const override
    {
        return AutoGeneratedValue;
    }

    ~FMapType() override = default;

private:
    static const FString AutoGeneratedValue;
    TUniquePtr<FType> KeyType;
    TUniquePtr<FType> ValueType;
};
