/* Copyright © 2022, Medelför OÜ. All rights reserved. */

#include "StructType.h"

const FString FStructType::VectorClass("/Script/CoreUObject.Vector");
const FString FStructType::RotatorClass("/Script/CoreUObject.Rotator");
const FString FStructType::VectorAutoGeneratedValue("0.0,0.0,0.0");
const FString FStructType::RotatorAutoGeneratedValue("0.0,0.0,0.0");
const FString FStructType::DefaultAutoGeneratedValue("");

FString FStructType::GetAutoGeneratedValueTransliteration() const
{
    if (GetIdentifierInfo().GetFullPath()
        .Equals(VectorClass, ESearchCase::IgnoreCase))
    {
        return VectorAutoGeneratedValue;
    }
    else if (GetIdentifierInfo().GetFullPath()
        .Equals(RotatorClass, ESearchCase::IgnoreCase))
    {
        return RotatorAutoGeneratedValue;
    }

    return DefaultAutoGeneratedValue;
}
